### ISSUE TITLE
pm events not triggering

### ISSUE THREAD

**Issue by nsharrok** [evocount/ember-leaflet-pm#55]
Hi,
I just trying out your pm-control and am unable to get the three events (create, drawstart and drawend) to trigger an action.
I've tried
```
<layers.marker-layer-pm 
    @onPm:Create={{action "create"}}
    @onPm:Drawend={{action "drawend"}}
  />
```
and
```
  <layers.pm-control
    @onPm:Create={{action "create"}}
    @onPm:Drawend={{action "drawend"}}
    />
```
and all other kinds of variants all without success.

Do you have a working demo?

**Comment by nsharrok** [comment]
Sorry,
Found the issue
```
  <layers.pm-control
    @onPm:create={{action "create"}}
    @onPm:drawend={{action "drawend"}}
    />
```

It was the capitalisation of the event name that I got wrong.

**Comment by ttill** [comment]
Great you were able to figure it out yourself, despite the readme being wrong. I just fixed that.
